apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: staging-

resources:
  - ../base

# Common labels for all resources
commonLabels:
  environment: staging

# Patches to apply for staging environment
patches:
  - path: patches/replica-count.yaml
    target:
      kind: Deployment
      name: .*

configMapGenerator:
  - name: staging-config
    literals:
      - ENVIRONMENT=staging
      - LOG_LEVEL=info

vars:
  - name: ENVIRONMENT
    objref:
      kind: ConfigMap
      name: staging-config
      apiVersion: v1
    fieldref:
      fieldpath: data.ENVIRONMENT
  - name: ARTIFACT_REGISTRY
    objref:
      kind: ConfigMap
      name: staging-config
      apiVersion: v1
    fieldref:
      fieldpath: data.ARTIFACT_REGISTRY
  - name: IMAGE_TAG
    objref:
      kind: ConfigMap
      name: staging-config
      apiVersion: v1
    fieldref:
      fieldpath: data.IMAGE_TAG
  - name: PROJECT_ID
    objref:
      kind: ConfigMap
      name: staging-config
      apiVersion: v1
    fieldref:
      fieldpath: data.PROJECT_ID 