apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service
  namespace: healthcare-system
  labels:
    app: patient-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: patient-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: patient-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: patient-service-sa
      containers:
      - name: patient-service
        image: ${ARTIFACT_REGISTRY}/patient-service:${IMAGE_TAG}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "8080"
        - name: DB_NAME
          value: "patient_service"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: patient-service-db-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: patient-service-db-credentials
              key: password
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: patient-service-db-credentials
              key: host
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: patient-service-db-credentials
              key: port
        - name: DB_SSL
          value: "true"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: value
        - name: LOG_LEVEL
          value: "info"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
        - name: patient-service-config
          mountPath: /app/config
          readOnly: true
      volumes:
      - name: tmp-volume
        emptyDir: {}
      - name: patient-service-config
        configMap:
          name: patient-service-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: patient-service
  namespace: healthcare-system
  labels:
    app: patient-service
spec:
  selector:
    app: patient-service
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: patient-service-sa
  namespace: healthcare-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: patient-service-configmap
  namespace: healthcare-system
data:
  logging.json: |
    {
      "level": "info",
      "format": "json",
      "service": "patient-service"
    }
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: patient-service-pdb
  namespace: healthcare-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: patient-service 