apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: healthcare-system
  labels:
    app: fluent-bit
    k8s-app: fluent-bit-logging
spec:
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      labels:
        app: fluent-bit
        k8s-app: fluent-bit-logging
    spec:
      containers:
      - name: fluent-bit
        image: fluent/fluent-bit:1.9.9
        volumeMounts:
        - name: logging-config
          mountPath: /fluent-bit/etc/
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: logging-credentials
          mountPath: /var/run/secrets/google
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: logging-config
        configMap:
          name: logging-config
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: logging-credentials
        secret:
          secretName: logging-credentials