apiVersion: v1
kind: ConfigMap
metadata:
  name: logging-config
  namespace: healthcare-system
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf

    [INPUT]
        Name          tail
        Path          /var/log/containers/*healthcare-system*.log
        Parser        docker
        Tag           kube.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On

    [FILTER]
        Name          kubernetes
        Match         kube.*
        Kube_URL      https://kubernetes.default.svc.cluster.local:443
        Merge_Log     On
        K8S-Logging.Parser On
        K8S-Logging.Exclude Off

    [OUTPUT]
        Name          stackdriver
        Match         *
        google_service_credentials /var/run/secrets/google/key.json
        resource      k8s_container
        k8s_cluster_name healthcare-system-dev
        k8s_cluster_location asia-south1

  parsers.conf: |
    [PARSER]
        Name          docker
        Format        json
        Time_Key      time
        Time_Format   %Y-%m-%dT%H:%M:%S.%L
        Time_Keep     On 