apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy
spec:
  template:
    spec:
      containers:
      - name: dummy
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi 