version: '3.8'

services:
  # Authentication Service
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "8090:8080"
    environment:
      - NODE_ENV=development
      - PORT=8080
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/healthcare
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your-secret-key
      - JWT_EXPIRES_IN=24h
    depends_on:
      - db
      - redis
    networks:
      - healthcare-network
    volumes:
      - ./auth-service:/app
      - /app/node_modules

  # Patient Service
  patient-service:
    build:
      context: ./patient-service
      dockerfile: Dockerfile
    ports:
      - "8091:4001"
    environment:
      - NODE_ENV=development
      - PORT=4001
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/healthcare
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your-secret-key
    depends_on:
      - db
      - redis
      - auth-service
    networks:
      - healthcare-network
    volumes:
      - ./patient-service:/app
      - /app/node_modules

  # Doctor Service
  doctor-service:
    build:
      context: ./doctor-service
      dockerfile: Dockerfile
    ports:
      - "8092:4002"
    environment:
      - NODE_ENV=development
      - PORT=4002
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/healthcare
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your-secret-key
    depends_on:
      - db
      - redis
      - auth-service
    networks:
      - healthcare-network
    volumes:
      - ./doctor-service:/app
      - /app/node_modules

  # Appointment Service
  appointment-service:
    build:
      context: ./appointment-service
      dockerfile: Dockerfile
    ports:
      - "8093:4003"
    environment:
      - NODE_ENV=development
      - PORT=4003
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/healthcare
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your-secret-key
      - PATIENT_SERVICE_URL=http://patient-service:4001
      - DOCTOR_SERVICE_URL=http://doctor-service:4002
    depends_on:
      - db
      - redis
      - auth-service
      - patient-service
      - doctor-service
    networks:
      - healthcare-network
    volumes:
      - ./appointment-service:/app
      - /app/node_modules

  # Medical Records Service
  medical-records-service:
    build:
      context: ./medical-records-service
      dockerfile: Dockerfile
    ports:
      - "8095:4005"
    environment:
      - NODE_ENV=development
      - PORT=4005
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/healthcare
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your-secret-key
      - PATIENT_SERVICE_URL=http://patient-service:4001
    depends_on:
      - db
      - redis
      - auth-service
      - patient-service
    networks:
      - healthcare-network
    volumes:
      - ./medical-records-service:/app
      - /app/node_modules

  # PostgreSQL Database
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=healthcare
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - healthcare-network

  # Redis Cache
  redis:
    image: redis:alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - healthcare-network

networks:
  healthcare-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: 