apiVersion: apps/v1
kind: Deployment
metadata:
  name: medical-records-service
  namespace: healthcare-system
  labels:
    app: medical-records-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medical-records-service
  template:
    metadata:
      labels:
        app: medical-records-service
    spec:
      containers:
      - name: medical-records-service
        image: gcr.io/eastern-period-459411-i8/medical-records-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "8080"
        - name: DB_NAME
          value: "medical_records_service"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: medical-records-service-db-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: medical-records-service-db-credentials
              key: password
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: medical-records-service-db-credentials
              key: host
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: medical-records-service-db-credentials
              key: port
---
apiVersion: v1
kind: Service
metadata:
  name: medical-records-service
  namespace: healthcare-system
  labels:
    app: medical-records-service
spec:
  selector:
    app: medical-records-service
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  type: ClusterIP
