version: '3.8'

services:
  auth-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - PORT=8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=healthcare_user
      - DB_PASSWORD=healthcare_password
      - DB_NAME=auth_service
      - DB_SSL=false
      - JWT_SECRET=your-super-secret-key-change-in-production
      - JWT_EXPIRES_IN=24h
    depends_on:
      - postgres
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=healthcare_user
      - POSTGRES_PASSWORD=healthcare_password
      - POSTGRES_DB=auth_service
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 