steps:
# Install dependencies and run tests for each service
- name: 'node:18'
  id: 'test-patient-service'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    cd services/patient-service
    npm ci
    npm run lint
    npm test
  waitFor: ['-']

- name: 'node:18'
  id: 'test-appointment-service'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "Tests for appointment service would go here"
  waitFor: ['-']

- name: 'node:18'
  id: 'test-doctor-service'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "Tests for doctor service would go here"
  waitFor: ['-']

- name: 'node:18'
  id: 'test-notification-service'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "Tests for notification service would go here"
  waitFor: ['-']

- name: 'node:18'
  id: 'test-medical-records-service'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "Tests for medical records service would go here"
  waitFor: ['-']

# Security scanning
- name: 'aquasec/trivy'
  id: 'scan-code'
  args: ['fs', '--security-checks', 'vuln,config,secret', '--severity', 'HIGH,CRITICAL', '.']
  waitFor: ['-']

# SonarQube analysis
- name: 'sonarsource/sonar-scanner-cli:latest'
  id: 'sonarqube-analysis'
  args:
  - '-Dsonar.projectKey=healthcare-system'
  - '-Dsonar.sources=.'
  - '-Dsonar.host.url=${_SONAR_HOST_URL}'
  - '-Dsonar.login=${_SONAR_TOKEN}'
  - '-Dsonar.pullrequest.key=${_PR_NUMBER}'
  - '-Dsonar.pullrequest.branch=${_HEAD_BRANCH}'
  - '-Dsonar.pullrequest.base=${_BASE_BRANCH}'
  waitFor: ['test-patient-service', 'test-appointment-service', 'test-doctor-service', 'test-notification-service', 'test-medical-records-service']

# Build container images to validate Dockerfiles (but don't push)
- name: 'gcr.io/cloud-builders/docker'
  id: 'build-patient-service'
  args: [
    'build',
    '-t', 'patient-service-pr:${_PR_NUMBER}',
    './services/patient-service'
  ]
  waitFor: ['test-patient-service', 'scan-code']

- name: 'gcr.io/cloud-builders/docker'
  id: 'build-appointment-service'
  args: [
    'build',
    '-t', 'appointment-service-pr:${_PR_NUMBER}',
    './services/appointment-service'
  ]
  waitFor: ['test-appointment-service', 'scan-code']

- name: 'gcr.io/cloud-builders/docker'
  id: 'build-doctor-service'
  args: [
    'build',
    '-t', 'doctor-service-pr:${_PR_NUMBER}',
    './services/doctor-service'
  ]
  waitFor: ['test-doctor-service', 'scan-code']

- name: 'gcr.io/cloud-builders/docker'
  id: 'build-notification-service'
  args: [
    'build',
    '-t', 'notification-service-pr:${_PR_NUMBER}',
    './services/notification-service'
  ]
  waitFor: ['test-notification-service', 'scan-code']

- name: 'gcr.io/cloud-builders/docker'
  id: 'build-medical-records-service'
  args: [
    'build',
    '-t', 'medical-records-service-pr:${_PR_NUMBER}',
    './services/medical-records-service'
  ]
  waitFor: ['test-medical-records-service', 'scan-code']

# Scan container images for vulnerabilities
- name: 'aquasec/trivy'
  id: 'scan-patient-service-image'
  args: ['image', '--severity', 'HIGH,CRITICAL', 'patient-service-pr:${_PR_NUMBER}']
  waitFor: ['build-patient-service']

- name: 'aquasec/trivy'
  id: 'scan-appointment-service-image'
  args: ['image', '--severity', 'HIGH,CRITICAL', 'appointment-service-pr:${_PR_NUMBER}']
  waitFor: ['build-appointment-service']

- name: 'aquasec/trivy'
  id: 'scan-doctor-service-image'
  args: ['image', '--severity', 'HIGH,CRITICAL', 'doctor-service-pr:${_PR_NUMBER}']
  waitFor: ['build-doctor-service']

- name: 'aquasec/trivy'
  id: 'scan-notification-service-image'
  args: ['image', '--severity', 'HIGH,CRITICAL', 'notification-service-pr:${_PR_NUMBER}']
  waitFor: ['build-notification-service']

- name: 'aquasec/trivy'
  id: 'scan-medical-records-service-image'
  args: ['image', '--severity', 'HIGH,CRITICAL', 'medical-records-service-pr:${_PR_NUMBER}']
  waitFor: ['build-medical-records-service']

# Validate Terraform files
- name: 'hashicorp/terraform:1.4'
  id: 'terraform-validate'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    cd terraform
    terraform init -backend=false
    terraform validate
  waitFor: ['-']

# Validate Kubernetes manifests
- name: 'gcr.io/cloud-builders/kubectl'
  id: 'kubectl-validate'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    # Install kubeval
    wget https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz
    tar xf kubeval-linux-amd64.tar.gz
    
    # Validate all Kubernetes YAML files
    find kubernetes -name "*.yaml" -type f -exec ./kubeval {} \;
  waitFor: ['-']

# Post PR comment with results
- name: 'gcr.io/cloud-builders/curl'
  id: 'post-github-comment'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    cat > comment.json << EOF
    {
      "body": "✅ CI Validation Passed\n\n- All tests passed\n- Security scans completed\n- Docker builds validated\n- Infrastructure files validated"
    }
    EOF
    
    curl -s -X POST \
      -H "Authorization: token $$GITHUB_TOKEN" \
      -H "Content-Type: application/json" \
      --data @comment.json \
      "https://api.github.com/repos/${_GITHUB_OWNER}/${_GITHUB_REPO}/issues/${_PR_NUMBER}/comments"
  secretEnv: ['GITHUB_TOKEN']
  waitFor: ['scan-patient-service-image', 'scan-appointment-service-image', 'scan-doctor-service-image', 'scan-notification-service-image', 'scan-medical-records-service-image', 'terraform-validate', 'kubectl-validate', 'sonarqube-analysis']

substitutions:
  _SONAR_HOST_URL: 'http://sonarqube:9000'
  _SONAR_TOKEN: ''
  _PR_NUMBER: '0'
  _HEAD_BRANCH: ''
  _BASE_BRANCH: 'main'
  _GITHUB_OWNER: 'your-github-username'
  _GITHUB_REPO: 'healthcare-appointment-system'

availableSecrets:
  secretManager:
  - versionName: projects/${PROJECT_ID}/secrets/github-token/versions/latest
    env: 'GITHUB_TOKEN'

options:
  machineType: 'E2_HIGHCPU_8'
  dynamicSubstitutions: true 