name: Appointment Service CD

on:
  workflow_run:
    workflows: ["Appointment Service CI"]
    branches: [main]
    types:
      - completed

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name healthcare-cluster --region ${{ secrets.AWS_REGION }}
          
      - name: Update Kubernetes deployment
        run: |
          sed -i 's|\${ARTIFACT_REGISTRY}|harsha098|g' kubernetes/appointment-service/deployment.yaml
          sed -i 's|\${IMAGE_TAG}|latest|g' kubernetes/appointment-service/deployment.yaml
          sed -i 's|\${ENVIRONMENT}|dev|g' kubernetes/appointment-service/deployment.yaml
          kubectl apply -f kubernetes/appointment-service/deployment.yaml
          
      - name: Verify deployment
        run: |
          kubectl rollout status deployment/appointment-service -n healthcare-system
          
      - name: Notify on success
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_TITLE: "✅ Appointment Service deployed to DEV"
          SLACK_MESSAGE: "Deployment completed successfully"
          SLACK_COLOR: good 