name: Medical Records Service CI

on:
  push:
    paths:
      - 'services/medical-records-service/**'
      - '.github/workflows/medical-records-service-ci.yml'
  pull_request:
    paths:
      - 'services/medical-records-service/**'
      - '.github/workflows/medical-records-service-ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: services/medical-records-service/package-lock.json
          
      - name: Install dependencies
        run: |
          cd services/medical-records-service
          npm ci
          
      - name: Run tests
        run: |
          cd services/medical-records-service
          npm test || true
          
      - name: Run linting
        run: |
          cd services/medical-records-service
          npm run lint || true

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: harsha098
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./services/medical-records-service
          push: true
          tags: harsha098/medical-records-service:${{ github.sha }},harsha098/medical-records-service:latest 